### ISSUE TITLE
Model structure of FreeStyle

### ISSUE THREAD

**Issue by SYC-OldCat** [FreeStyleFreeLunch/FreeStyle#5]
I want to know where the dual-stream encoder and single-stream decoder feature modulation modules are located in the code.

**Comment by FreeStyleFreeLunch** [comment]
Our dual-stream encoder architecture and single-stream decoder architecture are primarily reflected in the flow of data within the U-Net. The specific code can be found in 'stable_diffusion_xl_test.py' and the U-Net architecture code.
